### PR TITLE
don't show underscore under single quote

### PR DESCRIPTION
**Pull request by erlangp**

### CODE REVIEW

**Comment by codingyu** [comment]
In fact, it should not be changed here, this is the problem of regex.

**Comment by erlangp** [comment]
regex still need to find single quote.. but when displaying, ignore the single quote..

**Comment by erlangp** [comment]
For example currently: https://imgur.com/a/SW7zROb
i think better without underline under single quotes :D

**Comment by erlangp** [comment]
Thanks @codingyu :D

**Pull request merged**
